#!/bin/bash
set -e

should_yes=''
if [[ "$1" == "-y" ]]; then
  should_yes='-y'
fi

## Install all dependencies ##
pkgs='nodejs node-gyp libssl-dev npm python3 default-jre clang'
if ! dpkg -s $pkgs >/dev/null 2>&1; then
  sudo apt-get install $pkgs $should_yes
fi

## Install npx globally ##
npm_pkgs='npx'
if ! npm list -g $npm_pkgs; then
  sudo npm i -g $npm_pkgs
fi

## Install emcc ##
if [ ! -d ./build/emsdk ]; then
  mkdir -p build
  cd build
  git clone https://github.com/emscripten-core/emsdk.git
  cd emsdk
  ./emsdk install latest
  ./emsdk activate latest
  source ./emsdk_env.sh
  read -p "Do you want to add emcc to your ~/.bashrc? (y/n) " -r
  if [[ $REPLY =~ ^[Yy](es)?$ ]]; then
    echo "source $PWD/emsdk_env.sh &>/dev/null" >> ~/.bashrc
  else
    echo "If you ever want to change your mind, simply add \"source $PWD/emsdk_env.sh &>/dev/null\" to your ~/.bashrc"
  fi
  cd .. # out of ./build/emsdk
  cd .. # out of ./build
fi

## Install npm packages everywhere ##
npm i && cd voxelscript_extension && npm i && cd client && npm i && cd ../server && npm i && cd ../..

