[package]
name = "voxel_engine"
version = "0.1.0"
authors = ["Louise Song <louise.s.song@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
three-d = "0.2.0"
tri-mesh = "0.5.0"
