#!/bin/bash
set -e

function import {
    mkdir -p $3
    wget $2 -O $1
    unzip -o $1 -x / -d $3
    rm $1
}

sudo apt install wget unzip cmake make g++ libx11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxext-dev libxcursor-dev libxinerama-dev libxi-dev libglm-dev libfreetype6-dev

import assets.zip https://www.dropbox.com/sh/ky2lb4fefc00xa6/AADN9dDNXM4EMZU-uPoFd49ra?dl=1 ./assets

cmake .
make debug
