#!/bin/bash
set -e

if [[ ! -d ./build/CMakeFiles/release ]]; then
  mkdir -p ./build/CMakeFiles/release
  cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./build/CMakeFiles/release
fi
cmake --build ./build/CMakeFiles/release --target voxelcraft
cd ./build/release
./vc $@ 2>&1 | tee ../../output.log

