#!/bin/bash
set -e

mkdir -p ./build/CMakeFiles/release
cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./build/CMakeFiles/release
cmake --build ./build/CMakeFiles/release --target voxelcraft
cd ./build/release
./vc $@ 2>&1 | tee ../../output.log

