#!/bin/bash
set -e

mkdir -p ./build/CMakeFiles/debug
cmake -DCMAKE_BUILD_TYPE=Debug -S . -B ./build/CMakeFiles/debug
cmake --build ./build/CMakeFiles/debug --target voxelcraft
cd ./build/debug
./vc $@ 2>&1 | tee ../../output.log

