#!/bin/bash
set -e

export CC=/usr/bin/gcc-9
export CXX=/usr/bin/g++-9
export CMAKE_BUILD_TYPE=Debug

if [[ ! -d ./build/CMakeFiles/debug ]]; then
  mkdir -p ./build/CMakeFiles/debug
  cmake -DCMAKE_BUILD_TYPE=Debug -S . -B ./build/CMakeFiles/debug
fi
cmake --build ./build/CMakeFiles/debug --target voxelcraft
cd ./build/debug
./vc $@ 2>&1 | tee ../../output.log

